import {useState} from 'react'
import {NavLink,Outlet,useLocation} from 'react-router-dom'
import {Activity,AlarmClock,BarChart3,BookOpen,ChevronDown,ClipboardCheck,FileText,FolderKanban,HelpCircle,Menu,Network,OctagonAlert,Radio,Search,Settings,ShieldCheck,UserCircle,X} from 'lucide-react'
import {useAuth} from '../lib/auth'

const primary=[['/dashboard','Overview',BarChart3],['/projects','Projects',FolderKanban],['/assets','Assets',Network],['/scans','Scans',Activity],['/findings','Findings',OctagonAlert],['/traffic','Traffic',Radio],['/alerts','Alerts',AlarmClock],['/assessments','Assessments',ClipboardCheck],['/reports','Reports',FileText]] as const
export default function Layout(){const {user,logout}=useAuth();const [mobile,setMobile]=useState(false);const location=useLocation();
  return <div className="app-shell"><aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><div className="brand-mark"><ShieldCheck/></div><div><b>NetSecure</b><span>ASSESS</span></div><button className="icon-button mobile-close" onClick={()=>setMobile(false)}><X/></button></div><div className="authorized-chip"><i/>Authorized use only</div><nav><span className="nav-label">Workspace</span>{primary.map(([to,label,Icon])=><NavLink key={to} to={to} onClick={()=>setMobile(false)} className={({isActive})=>isActive?'active':''}><Icon/><span>{label}</span>{label==='Alerts'&&<em>2</em>}</NavLink>)}{user?.role==='administrator'&&<><span className="nav-label second">Administration</span><NavLink to="/admin"><Settings/><span>Admin console</span></NavLink></>}<span className="nav-label second">Learn</span><NavLink to="/help"><BookOpen/><span>Learning center</span></NavLink><NavLink to="/ethics"><HelpCircle/><span>Ethics & safety</span></NavLink></nav><div className="sidebar-footer"><div className="mini-shield"><ShieldCheck/></div><div><b>Safety guardrails active</b><span>Private ranges · Rate limited</span></div></div></aside>{mobile&&<button className="scrim" onClick={()=>setMobile(false)} aria-label="Close navigation"/>}<main><div className="topbar"><button className="icon-button menu-button" onClick={()=>setMobile(true)}><Menu/></button><div className="breadcrumb"><span>NETSECURE</span><b>/</b><strong>{location.pathname.split('/')[1]?.replace('-',' ').toUpperCase()||'OVERVIEW'}</strong></div><div className="top-search"><Search/><input aria-label="Search" placeholder="Search assets, findings, IPs…"/><kbd>⌘ K</kbd></div><button className="user-button"><span>{user?.full_name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><b>{user?.full_name}</b><small>{user?.role}</small></div><ChevronDown/></button><button className="text-button" onClick={logout}>Sign out</button></div><div className="page"><Outlet/></div></main></div>}

