import {useEffect,useState} from 'react'
import {BookOpen,Code2,Database,ExternalLink,FileWarning,GraduationCap,KeyRound,Network,Scale,ShieldCheck,TriangleAlert,Users} from 'lucide-react'
import {api} from '../lib/api'
import {useAuth} from '../lib/auth'
import {PageHeader,Spinner} from '../components/ui'

export function Help(){return <><PageHeader eyebrow="Learn while you assess" title="Learning center" description="Concise references for interpreting evidence without overclaiming certainty."/><div className="learning-grid">{[{i:Network,t:'Ports and services',b:'A port is a numbered endpoint. An open port shows reachability—not automatically a vulnerability.'},{i:TriangleAlert,t:'Severity and risk',b:'Severity describes technical harm. Risk combines it with confidence, exposure, asset value, impact, controls, and status.'},{i:FileWarning,t:'False positives',b:'Banners and version matches can be incomplete. Reproduce safely, inspect configuration, and ask the service owner.'},{i:ShieldCheck,t:'Remediation workflow',b:'Validate, prioritize, change in a tested window, verify with a bounded re-scan, then preserve evidence.'},{i:Database,t:'Traffic metadata',b:'Connection summaries reveal patterns while minimizing sensitive content. Payloads are not retained by default.'},{i:Code2,t:'Detection rules',b:'Rules use constrained fields and thresholds. They cannot execute arbitrary code on the server.'}].map(({i:Icon,t,b})=><article className="learning-card" key={t}><Icon/><h2>{t}</h2><p>{b}</p><button className="link-button">Explore concept <ExternalLink/></button></article>)}</div><section className="panel glossary"><div className="panel-head"><div><span className="panel-kicker">QUICK REFERENCE</span><h2>Glossary</h2></div><BookOpen/></div><dl><div><dt>Asset</dt><dd>A device or system with value to the organization.</dd></div><div><dt>Exposure</dt><dd>How reachable a service is from potential threat sources.</dd></div><div><dt>Confidence</dt><dd>How strongly the evidence supports the observation.</dd></div><div><dt>Residual risk</dt><dd>Risk remaining after existing controls are considered.</dd></div><div><dt>CIDR</dt><dd>Notation describing an IP network, such as 10.20.0.0/28.</dd></div><div><dt>PCAP</dt><dd>A packet-capture file; imports should be authorized and data-minimized.</dd></div></dl></section></>}

export function Ethics(){return <><PageHeader eyebrow="Non-negotiable boundaries" title="Ethics & authorized-use policy" description="Security learning is valuable only when consent, scope, privacy, and operational safety come first."/><section className="ethics-hero"><Scale/><div><h2>Permission before packets</h2><p>Use NetSecure Assess only on systems you own or have explicit written permission to assess. Scope and purpose must be recorded before every scan.</p></div></section><div className="ethics-grid"><section className="panel allowed"><h2><ShieldCheck/>What this platform supports</h2><ul><li>Private-network TCP connect checks</li><li>Small, administrator-bounded target ranges</li><li>Service and security-configuration observations</li><li>Metadata-only traffic analysis</li><li>Transparent control and risk assessment</li><li>Human-validated remediation planning</li></ul></section><section className="panel prohibited"><h2><TriangleAlert/>What is prohibited</h2><ul><li>Unauthorized or internet-wide scanning</li><li>Credential attacks or brute force</li><li>Exploitation or malware delivery</li><li>Denial-of-service or resource exhaustion</li><li>Stealth, evasion, spoofing, or persistence</li><li>Payload harvesting or data exfiltration</li></ul></section></div><section className="policy-steps"><span>01</span><div><b>Confirm ownership</b><small>Obtain written authorization from the system owner.</small></div><span>02</span><div><b>Record exact scope</b><small>Identify permitted hosts, ports, times, and responsible contacts.</small></div><span>03</span><div><b>Minimize impact</b><small>Use the lowest safe rate and stop when behavior is unexpected.</small></div><span>04</span><div><b>Protect evidence</b><small>Retain only necessary metadata and follow institutional rules.</small></div></section></>}

export function Admin(){const {user}=useAuth();const [users,setUsers]=useState<any[]|null>(null);const [logs,setLogs]=useState<any[]|null>(null);useEffect(()=>{if(user?.role==='administrator'){api.get<any[]>('/admin/users').then(setUsers);api.get<any[]>('/audit-logs').then(setLogs)}},[user]);if(user?.role!=='administrator')return <><PageHeader title="Administrator access required" description="Your current role cannot view user or immutable audit records."/><div className="empty"><KeyRound/><h3>Restricted area</h3><p>Sign in with the documented development administrator account to explore this page.</p></div></>;if(!users||!logs)return <Spinner/>;return <><PageHeader eyebrow="Platform governance" title="Administration" description="Manage accounts, safety limits, and immutable security events."/><div className="metrics-grid three"><div className="admin-metric"><Users/><span><b>{users.length}</b><small>Active accounts</small></span></div><div className="admin-metric"><ShieldCheck/><span><b>16</b><small>Max concurrency</small></span></div><div className="admin-metric"><GraduationCap/><span><b>Demo</b><small>Environment mode</small></span></div></div><section className="panel"><div className="panel-head"><div><span className="panel-kicker">IMMUTABLE EVENTS</span><h2>Audit history</h2></div></div><div className="table-scroll"><table><thead><tr><th>Event</th><th>Entity</th><th>User</th><th>Source</th><th>Time</th></tr></thead><tbody>{logs.map(log=><tr key={log.id}><td><code>{log.action}</code></td><td>{log.entity_type||'—'}</td><td>{users.find(u=>u.id===log.user_id)?.full_name||'System'}</td><td>{log.source_ip||'local'}</td><td>{new Date(log.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></section></>}

