import {useState} from 'react'
import {Navigate} from 'react-router-dom'
import {ArrowRight,BookOpen,CheckCircle2,Eye,EyeOff,LockKeyhole,Network,ShieldCheck} from 'lucide-react'
import {useAuth} from '../lib/auth'
import {ErrorNotice} from '../components/ui'

export default function Login(){const {user,login}=useAuth();const [email,setEmail]=useState('researcher@netsecure.local');const [password,setPassword]=useState('ResearchDemo!2026');const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');if(user)return <Navigate to="/dashboard" replace/>
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await login(email,password)}catch(err){setError(err instanceof Error?err.message:'Unable to sign in')}finally{setBusy(false)}}
  return <div className="login-page"><section className="login-story"><div className="brand login-brand"><div className="brand-mark"><ShieldCheck/></div><div><b>NetSecure</b><span>ASSESS</span></div></div><div className="story-content"><div className="eyebrow light">DEFENSIVE SECURITY, CLEARLY UNDERSTOOD</div><h1>See the network.<br/><em>Strengthen the system.</em></h1><p>One educational workspace for safe discovery, traffic insight, risk assessment, and evidence-led remediation.</p><div className="story-features"><div><Network/><span><b>Safe by design</b><small>Private scopes and hard scan limits</small></span></div><div><BookOpen/><span><b>Built to teach</b><small>Transparent scores and practical guidance</small></span></div><div><CheckCircle2/><span><b>Ready to demonstrate</b><small>Rich sample data, zero network activity</small></span></div></div></div><div className="story-footer"><LockKeyhole/>Authorized, defensive, and educational use only</div></section><section className="login-panel"><form onSubmit={submit}><div className="mobile-brand"><ShieldCheck/><b>NetSecure Assess</b></div><span className="step-pill">SECURE WORKSPACE</span><h2>Welcome back</h2><p>Sign in to continue your authorized assessment.</p>{error&&<ErrorNotice message={error}/>}<label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<div className="password-field"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label><div className="form-row"><label className="checkbox"><input type="checkbox"/>Remember me</label><button type="button" className="link-button">Forgot password?</button></div><button className="primary wide" disabled={busy}>{busy?'Verifying…':'Enter workspace'}<ArrowRight/></button><div className="demo-callout"><b>Demo access is prefilled</b><span>Researcher account · simulated data only</span></div><small className="terms">By continuing, you agree to use this platform only on systems you own or are explicitly authorized to assess.</small></form></section></div>}

