import {useEffect,useState} from 'react'
import {ArrowRight,CalendarDays,FolderKanban,Plus,ShieldCheck,Users,X} from 'lucide-react'
import {Link} from 'react-router-dom'
import {api} from '../lib/api'
import type {Project} from '../types'
import {Empty,ErrorNotice,PageHeader,Spinner,Status} from '../components/ui'

export default function Projects(){const [items,setItems]=useState<Project[]|null>(null);const [open,setOpen]=useState(false);const [error,setError]=useState('');const [form,setForm]=useState({name:'',description:'',scope:'10.20.0.0/24'});const load=()=>api.get<Project[]>('/projects').then(setItems);useEffect(()=>{load()},[])
  const create=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await api.post('/projects',form);setOpen(false);setForm({name:'',description:'',scope:'10.20.0.0/24'});load()}catch(err){setError(err instanceof Error?err.message:'Could not create project')}}
  if(!items)return <Spinner/>;return <><PageHeader eyebrow="Authorized workspaces" title="Projects" description="Organize scopes, evidence, findings, and assessments around a documented authorization." actions={<button className="primary" onClick={()=>setOpen(true)}><Plus/>New project</button>}/><div className="project-summary"><div><FolderKanban/><span><b>{items.length}</b><small>Active projects</small></span></div><div><ShieldCheck/><span><b>100%</b><small>Scopes documented</small></span></div><div><Users/><span><b>4</b><small>Team members</small></span></div></div>{items.length===0?<Empty title="No projects yet" body="Create a project to establish an authorized scope."/>:<div className="project-grid">{items.map((project,index)=><Link className="project-card" to={`/projects/${project.id}`} key={project.id}><div className={`project-visual project-${index%3}`}><FolderKanban/><Status value={project.status}/></div><div className="project-body"><h2>{project.name}</h2><p>{project.description}</p><div className="scope"><span>AUTHORIZED SCOPE</span><code>{project.scope}</code></div><div className="project-meta"><span><CalendarDays/>Updated recently</span><b>Open workspace <ArrowRight/></b></div></div></Link>)}</div>}{open&&<div className="modal-wrap"><button className="modal-backdrop" onClick={()=>setOpen(false)}/><form className="modal" onSubmit={create}><button type="button" className="modal-x" onClick={()=>setOpen(false)}><X/></button><div className="eyebrow">New authorization boundary</div><h2>Create project</h2><p>Record the engagement context and the network range you are permitted to assess.</p>{error&&<ErrorNotice message={error}/>}<label>Project name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Campus Lab Baseline" required minLength={3}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Purpose, owner, and educational context"/></label><label>Authorized scope<input value={form.scope} onChange={e=>setForm({...form,scope:e.target.value})} required/><small>Comma-separated private IPv4 networks. Each individual scan is still limited to 64 hosts.</small></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary">Create project</button></div></form></div>}</>}

